### ISSUE TITLE
Profils utilisateurs incomplets

### ISSUE THREAD

**Issue by AmonAmaaarth** [InnovaLangues/self#1053]
Il peut encore manquer des informations dans les profils utilisateurs (établissements, filières, années d'étude) que ce soit le fait d'un ancien compte (pré-Nov 2015 et la refonte du formulaire d'inscription) ou du bug précédemment réglé sur l'enregistrement des filières.
Ces informations sont primordiales.
Il faudrait avertir l'utilisateur, une fois connecté et avant la passation du test, qu'il doit compléter son profil.
Je propose un message au-dessus du code session à entrer : 
Attention, votre profil est incomplet, veuillez cliquer sur votre nom en haut à droite et éditer vos informations. Merci.

**Comment by arnaudbey** [comment]
Pas de souci ! 
![np](http://i.giphy.com/140UNmvB4FPqGQ.gif)

**Comment by AmonAmaaarth** [comment]
Cool !
