### ISSUE TITLE
Fichier pdf individuel

### ISSUE THREAD

**Issue by AmonAmaaarth** [InnovaLangues/self#935]
Le fichier d'export des résultat individuel est assez... sommaire.
S'il est possible un jour d'avoir une meilleure mise en page, taille des caractères et un logo UGA ce serait bien, l'étudiant pourrait alors l'utiliser comme attestation de positionnement.

**Comment by arnaudbey** [comment]
si l'équipe usage veut bien me fournir un modèle de document, pas de souci ! ;)

**Comment by RemBM** [comment]
J'étais en train de le faire quand j'ai eu un doute : faudra surement que ça passe en BE.

**Comment by arnaudbey** [comment]
cc @purplefish32 @chalonn

**Comment by RemBM** [comment]
Juste pour l'idée, à faire valider, bien sûr. Peut-être avec le logo UGA LANSAD.

![self_idee_export_pdf](https://cloud.githubusercontent.com/assets/8793432/12451475/f1f76986-bf89-11e5-9000-82e0117111bc.jpg)

**Comment by RemBM** [comment]
Autre remarque : la date affichée est celle du jour de l'export alors qu'il faudrait la date de passation du test

**Comment by AmonAmaaarth** [comment]
Enlever LANSAD pour mettre _Service des Langues_ (tout court)

**Comment by AmonAmaaarth** [comment]
ajout du logo innova
